### ISSUE TITLE
Run only vulners

### ISSUE THREAD

**Issue by aidylewis** [vulnersCom/nmap-vulners#17]
I'd expect this command to run only the **vulners** script. 

```
 nmap -sV --version-all --script vulners -oX nmap.xml -iL sorted_hosts.out
```

But nmap seems to run other scripts, including **fingerprint-strings**. I am reticent to use a **not** expression as I can't understand what other scripts are being run. Default? 

How can I just run **vulners** as the only NSE script?
```Nmap version 7.70 ( https://nmap.org )```

Many thanks for this script.

**Comment by advaithm** [comment]
it runs the fingerprint strings as part of the -sV scan. you can not stop it from running the other scripts as vulners.nse needs the -sV output.
