### ISSUE TITLE
RedHat version strings on backporting 

### ISSUE THREAD

**Issue by aidylewis** [vulnersCom/nmap-vulners#18]
Unfortunately, RedHat doesn't update the service version string when a package
has been applied.  So even though Apache httpd 2.4.6 is riddled with
vulnerabilities "backporting" is applied from the latest stable version which
in this case is 2.4.39. The scan however provides a list of 2.4.6 CVEs (which could be false positives). Is there any solutions to this apart from examining change logs or RPM versions?

**Comment by AkikoOrenji** [comment]
I'd suggest using a scanner that supports authenticated scans so it can check which exact packages are being used.  I think the open source version of Nessus does it. 
It appears the purpose of this project is just for checking banner versions.  Trying to do any more would require a completely different project.

**Comment by aidylewis** [comment]
Thanks for the feedback. I can ask the user of the RedHat target to run an OVAL-compatible tool such as **oscap**. [Red Hat and OVAL compatibility](https://access.redhat.com/articles/221883). I parse the nmap XML from the **vulners** script and write to a DB which can be visualised through Grafana. I've added a *positive* field with Boolean content which I can update as false if the vulnerability proves to be.
