### ISSUE TITLE
http-vulners-regex not working without paths

### ISSUE THREAD

**Issue by mavensecurity** [vulnersCom/nmap-vulners#22]
Without `--script-args paths=something` http-vulners-regex it will not return any results.  It is not even apparent it is sending any traffic to the target.

With `--script-args paths=something` it will either use that file or when it fails to find that file it uses the default paths file.  Traffic is sent as expected; results may follow.

Version info:

> root@kali:~# nmap --version
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1d libssh2-1.8.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

Try this:
`root@kali:~# nmap -p80 --script http-vulners-regex -d php.testsparker.com
`

Result (truncated):
> PORT   STATE SERVICE
80/tcp open  http
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.95 seconds

The relevant but not-so-helpful `-d` output:

> NSE: Starting http-vulners-regex against php.testsparker.com (107.20.213.223:80).
NSE: Finished http-vulners-regex against php.testsparker.com (107.20.213.223:80).

Then try again with bogus path:

`root@kali:~# nmap -p80 --script http-vulners-regex --script-args paths=nosuchfile -d php.testsparker.com`

Results:

> PORT   STATE SERVICE
80/tcp open  http
| http-vulners-regex: 
|   localstart.asp: 
|_    cpe:/a:php:php:5.2.6

Nmap done: 1 IP address (1 host up) scanned in 3.78 seconds

Relevant section from `-d` debug:

> NSE: Starting http-vulners-regex against php.testsparker.com (107.20.213.223:80).
NSE: [http-vulners-regex 107.20.213.223:80] Trying to read paths from a specified file nosuchfile
NSE: [http-vulners-regex 107.20.213.223:80] No file found at nselib/data/nosuchfile, using local copy
NSE: [http-vulners-regex 107.20.213.223:80] Failed to open a file with paths
NSE: [http-vulners-regex 107.20.213.223:80] Trying to read paths from a default file http-vulners-paths.txt
NSE: [http-vulners-regex 107.20.213.223:80] Analyze path default.cfm

**Comment by GMedian** [comment]
Hello.

Sorry for a long delay. The quick fix I have just made should address the issue.
