### ISSUE TITLE
Change vulners.nse filename so that the repo can run with nmap in a single command

### ISSUE THREAD

**Issue by jordantsap** [vulnersCom/nmap-vulners#23]
I noiticed that this repo has the same nse filename with one that nmap is alrerady shipped in. Thia file is vulners.nse which exists in the default nmap scripting directory and thus nmap cannot run with:
--script vuln,nmap-vulners in a single command.

**Comment by vulnersCom** [comment]
That’s the same plugin.
No need to install it manually if you are using latest nmap.

**Comment by slunak** [comment]
Suggest adding this info to the readme. It is not obvious.
