### ISSUE TITLE
Error #486: Your port specifications are illegal.

### ISSUE THREAD

**Issue by j3rrey** [vulnersCom/nmap-vulners#27]
./nmapAutomator.sh 10.10.10.160 Vulns

Running Vuln scan on basic ports

Starting Nmap 7.80 ( https://nmap.org ) at 2020-02-28 14:10 CET
Error #486: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!

---------------------Finished all Nmap scans---------------------
Completed in 0 seconds

I guess this is a quick fix but was to lazy so far to check out ur script any idea ?

**Comment by GMedian** [comment]
The script you are using does not seem familiar. So cannot help you here.
