### ISSUE TITLE
Can nmap-valners help to check cve for web application?

### ISSUE THREAD

**Issue by rainishjj** [vulnersCom/nmap-vulners#31]
Dear,
    I have a web application created with java. I want to check if there exist any cve problem. I want to make sure if this way is ok?
I started my web application using tomcat,so I get the port for it. Use this tool to scan, I found anything output.
the command I execute like: 
nmap --script nmap-vulners,vulscan --script-args vulscandb=scipvuldb.csv -sV -p8080 ip
 and get the result like:
![image](https://user-images.githubusercontent.com/28695335/94090232-b588dc80-fe47-11ea-9142-cc5a4f0d3b44.png)
no any problem report, So I doubt if there any problem, please also support some sample such like some website I can scan to get the problem report, So I check if the tool is work well.
Please help!

**Comment by GMedian** [comment]
Hello.

First of all, are you sure there is a problem? The script can only tell CVEs if nmap itself detects cpe correctly, so the lack of output may lie there.
To  check the output you can scan the nmap host:

`nmap -sV --script vulners -p80 scanme.nmap.org`
