### ISSUE TITLE
Scripts error

### ISSUE THREAD

**Issue by Swiper97** [vulnersCom/nmap-vulners#42]
Hey everyone so when I use this command to check vulnerabilities on my router (map --script vulscan,nmap-vulners -sV 196.168.0.1) it gives me this error

Starting Nmap 7.91 ( https://nmap.org ) at 2021-04-12 10:09 EDT
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:821: directory '/usr/bin/../share/nmap/scripts/nmap-vulners' found, but will not match without '/'
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nse_main.lua:821: in local 'get_chosen_scripts'
        /usr/bin/../share/nmap/nse_main.lua:1312: in main chunk
        [C]: in ?

QUITTING!

I installed both scripts correctly on the nmap scripts folder but doesnt work, someone hlep me plz

**Comment by Swiper97** [comment]
So instead of writting --scripts, I only needed to write --script-args

**Comment by Bonk001** [comment]
> So instead of writting --scripts, I only needed to write --script-args

It worked for me
