### ISSUE TITLE
Is there a way to use an offline CSV file or a privately hosted Vulners CVE database?

### ISSUE THREAD

**Issue by oshall** [vulnersCom/nmap-vulners#7]
I'm curious is there a way to use the python script (https://github.com/vulnersCom/api) or https://github.com/vulnersCom/getsploit for using an offline copy of the vulners database instead of sending the software versions that are detected over the Internet. If the local/offline option is not possible how would we use a privately hosted alternative?

**Comment by vulnersCom** [comment]
Hello!
It's definitely hard. Because of the tons of logic at the backend for the detection.
Unfortunately, on-premise Vulners database is in early-beta.

**Comment by kbensimoun** [comment]
Hello,

A follow up question to @vulnersCom 
I'm also trying to use an offline copy of the vulners db. Is it possible to get into the early beta?

**Comment by safir2306** [comment]
Hey Guys,

Fell on this a little late in the game, but maybe if you are interestred, check out https://github.com/scipag/vulscan this provides the possibility for offline vuln scanning. just need to update the csv files manually though. Check it out.

Cheers

**Comment by wuyasec** [comment]
I use scripts to detect websites, but scripts do not prompt.

**Comment by vulnersCom** [comment]
Hi everyone! Unfortunately, we are not planning to make it offline available. It looks quite impossible for us.
