### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [vulnersCom/nmap-vulners#8]
Hi my OS is Linux kali 4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux
i copy vulners.nse file in /usr/share/nmap/scripts and when i start 
nmap -sV --script vulners target i get this 

Starting Nmap 7.60 ( https://nmap.org ) at 2018-01-07 19:46 EET
NSE: failed to initialize the script engine:
/usr/local/bin/../share/nmap/nse_main.lua:821: 'vulners' did not match a category, filename, or directory
stack traceback:
	[C]: in function 'error'
	/usr/local/bin/../share/nmap/nse_main.lua:821: in local 'get_chosen_scripts'
	/usr/local/bin/../share/nmap/nse_main.lua:1312: in main chunk
	[C]: in ?

QUITTING!

another scripts is working fine

**Comment by Keldorb** [comment]
For all other who encounter this problem. I guess it was a problem with downloading the file the right way. Please check if the file is correctly downloaded and does contain the lua and not the html sourcecode from github.
